# Generated by Django 5.2.5 on 2025-10-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_notification'),
    ]

    operations = [
    ]
